version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_HOST: postgres.dist-crawler
      POSTGRES_DB: price_data
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend

  web-api:
    image: api
    ports:
      - "8001:8001"
    env_file: .env
    networks:
      - backend
    depends_on:
      - postgres

  crawler:
    image: crawler
    ports:
      - "8002:8002"
    env_file: .env
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    networks:
      - backend
    depends_on:
      - postgres

  discovery:
    image: discovery
    ports:
      - "8003:8003"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    env_file: .env
    networks:
      - backend
    depends_on:
      - postgres

  scheduler:
    image: scheduler
    ports:
      - "8004:8004"
    env_file: .env
    networks:
      - backend
    depends_on:
      - discovery
      - crawler

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    networks:
      - backend

volumes:
  pg_data:

networks:
  backend:
    external: true
    name: dist-crawler_backend
